### PR TITLE
TRA-258: Require authentication to access module

### PR DESCRIPTION
**Pull request by isears**
**Why**
The import and export pages of this module are accessible without authentication (e.g. `http://localhost:8080/openmrs/module/dataexchange/import.form`)

**What Changed**
A 401 Unauthorized response is now returned if an unauthenticated user attempts to access the module.

**Decisions Made**
Auth checks are accomplished through the implementation of a simple implementation of `javax.servlet.Filter`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@isears did you consider simply using the require privilege tag? https://github.com/openmrs/openmrs-module-legacyui/blob/1.6.0/omod/src/main/webapp/admin/concepts/conceptClassList.jsp#L3

**Comment by isears** [comment]
@dkayiwa I hadn't, but that definitely looks like a better way to do it. Is there already a data-export privilege I can use? Or a similar privilege I can piggyback off of?

**Comment by dkayiwa** [comment]
@isears looking at this again, i think we allow exporting concepts without authentication just like here: https://github.com/openmrs/openmrs-module-legacyui/blob/master/omod/src/main/webapp/dictionary/index.jsp#L60

**Comment by isears** [comment]
@dkayiwa what about the import functionality? Is it safe to expose that publicly?

**Comment by dkayiwa** [comment]
@isears oh that one requires privileges like `"Manage Concepts"

**Comment by isears** [comment]
Ok closing for now. I'll start a thread for further discussion on the security mailing list

**Pull request closed without merging**
